Add TravisCi Badge
future-link/deltaweb pull request #19
Opened 2017-08-28 06:48 UTC by atnanasi

2017-08-28 09:33 UTC, rinsuki requested changes

2017-08-28 09:33 UTC, Petitsurume commented on README.md
> +# deltaweb [![Build Status](https://travis-ci.org/Petitsurume/deltaweb.svg?branch=master)](https://travis-ci.org/Petitsurume/deltaweb)
改行して

2017-08-29 07:55 UTC, atnanasi commented on README.md
> +# deltaweb [![Build Status](https://travis-ci.org/Petitsurume/deltaweb.svg?branch=master)](https://travis-ci.org/Petitsurume/deltaweb)
オッケー

2017-08-29 14:27 UTC, rinsuki approved these changes
LGTM

2017-08-29 14:27 UTC, merged